modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/matthewperiut/cryonicconfig/issues"
license = "MIT"

[[mods]]
modId = "cryonicconfig"
version = "${version}"
displayName = "Cryonic Config"
authors = "Slainlight"
description = '''
Chill Minimal Config API
'''
logoFile = "assets/cryonicconfig/logo.png"

[[dependencies.cryonicconfig]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryonicconfig]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.11]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cryonicconfig.mixins.json"
